### ISSUE TITLE
DetectRaptor.yaml - find zip URL fail

### ISSUE THREAD

**Issue by ekt0-syn** [Velocidex/velociraptor-docs#748]
The first http request is used to first check for version timestamp and find zip url of DetectRaptor package. 

The first request is set to https://api.github.com/repos/mgreen27/DetectRaptor/releases.

I don't know if it's due to an update on GitHub side, but right now the Server.ImportDetectRaptor server artifact fails to execute properly because GitHub API wants the User-Agent header to be set. Below is the corresponding Log:

> Request forbidden by administrative rules. Please make sure your request has a User-Agent header (https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required). Check https://developer.github.com for other possible causes. 

So I propose to pass a user-agent value in the user_gent argument of http_client() on the first call (PR to come). That way the forbidden error is no longer returned and the import is successful.

**Comment by scudette** [comment]
I see  - interestingly 0.7.1 introduced the ability to set the user agent but inadvertently cleared the user agent when not specified

https://github.com/Velocidex/velociraptor/commit/4c31254a8ffabc1ae0d5685c509c6f4847e68488

So now in 0.7.1 if a user agent is not specified it does not send one at all. But before it  used the default golang one. This is likely a regression actually.

**Comment by mgreen27** [comment]
@ekt0-syn sounds good - I assume your using 0.7.1 - I wonder if we are better using the 
```headers=dict(`User-Agent`="Velociraptor - DetectRaptor")``` 
param as this will make the fix cross version compatible

**Comment by mgreen27** [comment]
Just added https://github.com/Velocidex/velociraptor-docs/pull/750

**Comment by ekt0-syn** [comment]
Perfect, thanks!
