### ISSUE TITLE
FYI: CIS-CAT Lite

### ISSUE THREAD

**Issue by wmunyan** [Velocidex/velociraptor-docs#796]
Hello!  This isn't really an "issue" or "bug", but I came across your documentation regarding the use of CIS-CAT Lite here: https://docs.velociraptor.app/exchange/artifacts/pages/windows.audit.ciscat_lite/. 

I wanted to let you know you could actually automate the process and avoid having to register with CIS by using their publicly available API to download the latest version of CIS-CAT Lite.  Documentation for that API is at https://ssapi.docs.cisecurity.org/en/latest/endpoints/cis-cat-lite-latest.html.

I am sure automating the full process of downloading, unzipping and running CIS-CAT Lite, and uploading the HTML report could be a helpful addition to your tools.  Hope it helps!

**Comment by ablescia** [comment]
Dear @wmunyan, I'm Antonio Blescia, the CIS-CAT Lite artifact author.

Thanks for your submission, I will update the artifact to automate the download process 🤗.

**Comment by ablescia** [comment]
Dear @wmunyan,
you can find the pull request [here](https://github.com/Velocidex/velociraptor-docs/pull/843).

Best regards.

**Comment by ablescia** [comment]
Dear @scudette , can you close this issue? Thanks.

**Comment by scudette** [comment]
Thanks 🙏
