### ISSUE TITLE
Procedure to add a comunity exchange VQL module

### ISSUE THREAD

**Issue by RCarras** [Velocidex/velociraptor-docs#860]
Hello,

I'd like to add a new VQL module to velociraptor comunity exchange, which is the procedure?

Thanks!

**Comment by scudette** [comment]
Go to the artifact exchange here https://docs.velociraptor.app/exchange/

Then click on the button that says share your own artifact. This will redirect to GitHub and allow you to paste your artifact into the editor then prepare a pr to the repository.

Thanks 🙏
