### ISSUE TITLE
Support author field in notebook artifacts

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor-docs#879]
The "author" field does not cause any issues in the artifact editor nor in the notebook creator, but the documentation builder script in this project [fails](https://github.com/Velocidex/velociraptor-docs/actions/runs/9929670918/job/27427517738).

**Comment by scudette** [comment]
This problem is not with the author field but the output field which was added recently. I updated the syntax checked from 0.6.9 to 0.72.4 to support the latest artifact syntax
